### ISSUE TITLE
Cheating loophole

### ISSUE THREAD

**Issue by Tylercastle** [desi-programmer/flutter-quizstar#2]
It looks like as it is set up right now you can spam the first answer and it moves you all the way to the ends. 
(For a 10question quiz, Tapping the first correct answer 10 times lands you on the result page with perfect score. 

It also allows for greater than 100% score if you can tap more times in the 2 seconds window between switching questions

**Comment by desi-programmer** [comment]
Ah, Sorry I think its' too late. But I Fixed It.
