### ISSUE TITLE
Could you specify the license that applies to the code?

### ISSUE THREAD

**Issue by xanguera** [desi-programmer/flutter-quizstar#6]
Hi,
thank you for putting together such a nice app.
Would you be able to add a license to the code? I would like to use it in a project but unless there is a license associated to it I am afraid I can not.
I see Github explains what possible licenses you can use in [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)

**Comment by desi-programmer** [comment]
Just Added That !
